name: Auto Commit

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Auto Commit Bot"
          git config --global user.email "your-email@example.com"

      - name: Randomly Update Files
        run: |
          # Pick a random file to modify or create a new one
          FILES=("README.md" "config.json" "docs/setup.txt" "src/settings.py" "CHANGELOG.md" "src/components/ComponentA.js" "docs/CONTRIBUTING.md" "src/utils/helpers.js" "src/styles/global.css" "src/components/NavBar.js" "docs/api.md" "src/utils/logger.js")
          RANDOM_FILE=${FILES[$RANDOM % ${#FILES[@]}]}

          # Make some changes based on the file selected
          if [[ "$RANDOM_FILE" == "README.md" ]]; then
            echo "Added new feature details and upcoming roadmap $(date)" >> README.md
          elif [[ "$RANDOM_FILE" == "config.json" ]]; then
            echo "{\"feature_flag\": true, \"version\": \"$(date)\"}" > config.json
          elif [[ "$RANDOM_FILE" == "docs/setup.txt" ]]; then
            echo "Fixed typos in setup instructions and added troubleshooting steps $(date)" >> docs/setup.txt
          elif [[ "$RANDOM_FILE" == "src/settings.py" ]]; then
            echo "# Added new settings to support feature toggle $(date)" >> src/settings.py
          elif [[ "$RANDOM_FILE" == "CHANGELOG.md" ]]; then
            echo "- $(date): Updated settings for improved performance in UI" >> CHANGELOG.md
          elif [[ "$RANDOM_FILE" == "src/components/ComponentA.js" ]]; then
            echo "// Added event handler for new button click functionality $(date)" >> src/components/ComponentA.js
          elif [[ "$RANDOM_FILE" == "docs/CONTRIBUTING.md" ]]; then
            echo "- Updated contribution guidelines for API integration $(date)" >> docs/CONTRIBUTING.md
          elif [[ "$RANDOM_FILE" == "src/utils/helpers.js" ]]; then
            echo "// Added utility function for better date formatting $(date)" >> src/utils/helpers.js
          elif [[ "$RANDOM_FILE" == "src/styles/global.css" ]]; then
            echo "body { background-color: #f4f4f4; font-family: Arial, sans-serif; } /* Updated for readability $(date) */" >> src/styles/global.css
          elif [[ "$RANDOM_FILE" == "src/components/NavBar.js" ]]; then
            echo "// Improved responsiveness for mobile view $(date)" >> src/components/NavBar.js
          elif [[ "$RANDOM_FILE" == "docs/api.md" ]]; then
            echo "Added new endpoint details for user authentication $(date)" >> docs/api.md
          elif [[ "$RANDOM_FILE" == "src/utils/logger.js" ]]; then
            echo "// Added logging for user authentication process $(date)" >> src/utils/logger.js
          fi

      - name: Generate Dynamic Commit Message
        id: commit_message
        run: |
          # Create a list of commit messages with variety and context
          COMMIT_MESSAGES=(
            "Updated feature flags to support new UI component"
            "Fixed minor typo in setup instructions"
            "Enhanced user login flow for better error handling"
            "Improved logging for user interactions"
            "Refactored global styles for consistency"
            "Optimized event handler in ComponentA.js"
            "Fixed broken link in API documentation"
            "Added new utility function for date manipulation"
            "Updated changelog with details for version 2.1.0"
            "Updated NavBar.js to improve mobile responsiveness"
            "Refactored authentication service for scalability"
            "Fixed outdated API endpoint in documentation"
            "Updated build configurations for production optimization"
            "Refined setup documentation for easier onboarding"
            "Improved error handling in logger.js"
            "Fixed UI misalignment on smaller screens"
            "Enhanced form validation for better user experience"
            "Updated README with new feature rollout plan"
            "Improved performance of date parsing function"
            "Refined global CSS styles for better consistency"
          )
          RANDOM_COMMIT_MESSAGE=${COMMIT_MESSAGES[$RANDOM % ${#COMMIT_MESSAGES[@]}]}
          echo "::set-output name=message::$RANDOM_COMMIT_MESSAGE"

      - name: Commit changes
        run: |
          git add .
          git commit -m "${{ steps.commit_message.outputs.message }}"
          git push
