name: Auto Commit

on:
  schedule:
     - cron: '* * * * *'  # Runs every minute

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Important for manual authentication

      - name: Set up Git
        run: |
          git config --global user.name "Auto Commit Bot"
          git config --global user.email "your-email@example.com"

      - name: Randomly Update Files
        run: |
          FILES=("README.md" "config.json" "docs/setup.txt" "src/settings.py" "CHANGELOG.md")
          RANDOM_FILE=${FILES[$RANDOM % ${#FILES[@]}]}

          echo "Updating $RANDOM_FILE"
          echo "Auto update on $(date)" >> $RANDOM_FILE

      - name: Generate Commit Message
        id: commit_message
        run: |
          MESSAGES=("Updated docs" "Refactored settings" "Minor fixes" "Updated changelog" "Tweaked configurations")
          RANDOM_MESSAGE=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}
          echo "message=$RANDOM_MESSAGE" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git add .
          git commit -m "${{ env.message }}" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main || echo "No changes to push"
